language: python
python:
  - 2.6
  - 2.7
env:
  - DJANGO_VERSION=1.3.5
  - DJANGO_VERSION=1.4.3
  - DJANGO_VERSION=1.5.1
install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install -q -r requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors
script:
  - coverage run manage.py test doubleclick_protection
after_success:
  - coveralls
notifications:
  email:
    - henning.kage@gmail.com
