language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO="django==1.5.1 --use-mirrors"
  - DJANGO="django==1.4.3 --use-mirrors"
  - DJANGO="django==1.3.5 --use-mirrors"
install:
  - pip install $DJANGO
script:
  - python doubleclick_protection/runtests/runtests.py